apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: windows-11-x86-64-iso
  namespace: images
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  source:
    http:
      url: "https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26200.6584.250915-1905.25h2_ge_release_svc_refresh_CLIENT_CONSUMER_x64FRE_en-us.iso"
  storage:
    resources:
      requests:
        storage: 8Gi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: windows-11-x86-64-iso
  namespace: images
  labels:
    kubevirt.io/iso: 'true'
    template.kubevirt.io/architecture: amd64
    instancetype.kubevirt.io/default-instancetype: u1.large
    instancetype.kubevirt.io/default-preference: windows.11.virtio
spec:
  source:
    pvc:
      name: windows-11-x86-64-iso
      namespace: images

